name = "cf-workers-sub"
main = "_worker.js"
compatibility_date = "2025-04-01"

[assets]
directory = "./dist/"

[vars]
LINK = """"""
TOKEN = "auto"
TGTOKEN = ""
TGID = ""
SUBAPI = "SUBAPI.fxxk.dedyn.io"
SUBCONFIG = "https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/config/ACL4SSR_Online_MultiCountry.ini"
SUBNAME = "CF-Workers-SUB"
SUBUPTIME = "6" 